# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2004 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C09
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe


Borland:  \
	Interfaces.exe \
	Interfaces2.exe \
	UseDatabase.exe \
	UseDatabase2.exe \
	UseDatabase3.exe \
	Offset.exe \
	Duplicate.exe \
	VirtualBase.exe \
	VirtualBase2.exe \
	VirtualBase3.exe \
	VirtInit.exe \
	BreakTie.exe \
	Dominance.exe \
	Dominance2.exe \
	Vendor.$(OBJEXT) \
	Paste.exe \
	TESTHEADER_Database.exe \
	TESTHEADER_Countable.exe \
	TESTHEADER_DBConnection.exe \
	TESTHEADER_DBConnection2.exe \
	TESTHEADER_Vendor.exe

Microsoft:  \
	Interfaces.exe \
	Interfaces2.exe \
	UseDatabase.exe \
	UseDatabase2.exe \
	UseDatabase3.exe \
	Offset.exe \
	Duplicate.exe \
	VirtualBase.exe \
	VirtualBase2.exe \
	VirtualBase3.exe \
	VirtInit.exe \
	BreakTie.exe \
	Dominance.exe \
	Dominance2.exe \
	Vendor.$(OBJEXT) \
	Paste.exe \
	TESTHEADER_Database.exe \
	TESTHEADER_Countable.exe \
	TESTHEADER_DBConnection.exe \
	TESTHEADER_DBConnection2.exe \
	TESTHEADER_Vendor.exe

g++:  \
	Interfaces.exe \
	Interfaces2.exe \
	UseDatabase.exe \
	UseDatabase2.exe \
	UseDatabase3.exe \
	Offset.exe \
	Duplicate.exe \
	VirtualBase.exe \
	VirtualBase2.exe \
	VirtualBase3.exe \
	VirtInit.exe \
	BreakTie.exe \
	Dominance.exe \
	Dominance2.exe \
	Vendor.$(OBJEXT) \
	Paste.exe \
	TESTHEADER_Database.exe \
	TESTHEADER_Countable.exe \
	TESTHEADER_DBConnection.exe \
	TESTHEADER_DBConnection2.exe \
	TESTHEADER_Vendor.exe

edg:  \
	Interfaces.exe \
	Interfaces2.exe \
	UseDatabase.exe \
	UseDatabase2.exe \
	UseDatabase3.exe \
	Offset.exe \
	Duplicate.exe \
	VirtualBase.exe \
	VirtualBase2.exe \
	VirtualBase3.exe \
	VirtInit.exe \
	BreakTie.exe \
	Dominance.exe \
	Dominance2.exe \
	Vendor.$(OBJEXT) \
	Paste.exe \
	TESTHEADER_Database.exe \
	TESTHEADER_Countable.exe \
	TESTHEADER_DBConnection.exe \
	TESTHEADER_DBConnection2.exe \
	TESTHEADER_Vendor.exe

Metrowerks:  \
	Interfaces.exe \
	Interfaces2.exe \
	UseDatabase.exe \
	UseDatabase2.exe \
	UseDatabase3.exe \
	Offset.exe \
	Duplicate.exe \
	VirtualBase.exe \
	VirtualBase2.exe \
	VirtualBase3.exe \
	VirtInit.exe \
	BreakTie.exe \
	Dominance.exe \
	Dominance2.exe \
	Vendor.$(OBJEXT) \
	Paste.exe \
	TESTHEADER_Database.exe \
	TESTHEADER_Countable.exe \
	TESTHEADER_DBConnection.exe \
	TESTHEADER_DBConnection2.exe \
	TESTHEADER_Vendor.exe

DigitalMars:  \
	Interfaces.exe \
	Interfaces2.exe \
	UseDatabase.exe \
	UseDatabase2.exe \
	UseDatabase3.exe \
	Offset.exe \
	Duplicate.exe \
	VirtualBase.exe \
	VirtualBase2.exe \
	VirtualBase3.exe \
	VirtInit.exe \
	BreakTie.exe \
	Dominance.exe \
	Dominance2.exe \
	Vendor.$(OBJEXT) \
	Paste.exe \
	TESTHEADER_Database.exe \
	TESTHEADER_Countable.exe \
	TESTHEADER_DBConnection.exe \
	TESTHEADER_DBConnection2.exe \
	TESTHEADER_Vendor.exe

CodeWizard:
	CodeWizard *.cpp

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.o
	del *.obj
	del *.exe
	del *.tds
	del *.map
else
	rm -f *.o *.obj *.exe *.tds *.map
endif


Interfaces.exe: Interfaces.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Interfaces2.exe: Interfaces2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

UseDatabase.exe: UseDatabase.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

UseDatabase2.exe: UseDatabase2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

UseDatabase3.exe: UseDatabase3.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Offset.exe: Offset.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Duplicate.exe: Duplicate.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

VirtualBase.exe: VirtualBase.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

VirtualBase2.exe: VirtualBase2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

VirtualBase3.exe: VirtualBase3.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

VirtInit.exe: VirtInit.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

BreakTie.exe: BreakTie.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Dominance.exe: Dominance.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Dominance2.exe: Dominance2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Vendor.$(OBJEXT): Vendor.cpp


Paste.exe: Vendor.$(OBJEXT) Paste.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Paste.$(OBJEXT): Paste.cpp

TESTHEADER_Database.exe: TESTHEADER_Database.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_Countable.exe: TESTHEADER_Countable.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_DBConnection.exe: TESTHEADER_DBConnection.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_DBConnection2.exe: TESTHEADER_DBConnection2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_Vendor.exe: TESTHEADER_Vendor.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

