# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2004 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C06
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe


Borland:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	Generators.$(OBJEXT) \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	Counted.$(OBJEXT) \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe \
	TESTHEADER_Generators.exe \
	TESTHEADER_NumStringGen.exe \
	TESTHEADER_PrintSequence.exe \
	TESTHEADER_NString.exe \
	TESTHEADER_Counted.exe \
	TESTHEADER_Inventory.exe \
	TESTHEADER_copy_if.exe

Microsoft:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	Generators.$(OBJEXT) \
	FunctionObjects.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	Counted.$(OBJEXT) \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe \
	TESTHEADER_Generators.exe \
	TESTHEADER_NumStringGen.exe \
	TESTHEADER_PrintSequence.exe \
	TESTHEADER_NString.exe \
	TESTHEADER_Counted.exe \
	TESTHEADER_Inventory.exe \
	TESTHEADER_copy_if.exe

g++:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	Generators.$(OBJEXT) \
	FunctionObjects.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	Counted.$(OBJEXT) \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe \
	TESTHEADER_Generators.exe \
	TESTHEADER_NumStringGen.exe \
	TESTHEADER_PrintSequence.exe \
	TESTHEADER_NString.exe \
	TESTHEADER_Counted.exe \
	TESTHEADER_Inventory.exe \
	TESTHEADER_copy_if.exe

edg:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	Generators.$(OBJEXT) \
	FunctionObjects.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	Counted.$(OBJEXT) \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe \
	TESTHEADER_Generators.exe \
	TESTHEADER_NumStringGen.exe \
	TESTHEADER_PrintSequence.exe \
	TESTHEADER_NString.exe \
	TESTHEADER_Counted.exe \
	TESTHEADER_Inventory.exe \
	TESTHEADER_copy_if.exe

Metrowerks:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	Generators.$(OBJEXT) \
	FunctionObjects.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	Counted.$(OBJEXT) \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe \
	TESTHEADER_Generators.exe \
	TESTHEADER_NumStringGen.exe \
	TESTHEADER_PrintSequence.exe \
	TESTHEADER_NString.exe \
	TESTHEADER_Counted.exe \
	TESTHEADER_Inventory.exe \
	TESTHEADER_copy_if.exe

DigitalMars:  \
	CopyInts.exe \
	CopyStrings.exe \
	CopyVector.exe \
	InsertVector.exe \
	CopyInts2.exe \
	CopyStrings2.exe \
	ReplaceStrings.exe \
	CopyInts3.exe \
	CopyIntsToFile.exe \
	CopyIntsFromFile.exe \
	GreaterThanN.exe \
	CopyInts4.exe \
	CountNotEqual.exe \
	Generators.$(OBJEXT) \
	FunctionObjects.exe \
	FBinder.exe \
	BinderValue.exe \
	PtrFun1.exe \
	PtrFun2.exe \
	MemFun1.exe \
	MemFun2.exe \
	FindBlanks.exe \
	MemFun3.exe \
	ComposeTry.exe \
	ComposeFinal.exe \
	FillGenerateTest.exe \
	Counting.exe \
	Manipulations.exe \
	SearchReplace.exe \
	Comparison.exe \
	Removing.exe \
	SortedSearchTest.exe \
	MergeTest.exe \
	SetOperations.exe \
	Counted.$(OBJEXT) \
	ForEach.exe \
	Transform.exe \
	CalcInventory.exe \
	TransformNames.exe \
	SpecialList.exe \
	NumericTest.exe \
	TESTHEADER_Generators.exe \
	TESTHEADER_NumStringGen.exe \
	TESTHEADER_PrintSequence.exe \
	TESTHEADER_NString.exe \
	TESTHEADER_Counted.exe \
	TESTHEADER_Inventory.exe \
	TESTHEADER_copy_if.exe

CodeWizard:
	CodeWizard *.cpp

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.o
	del *.obj
	del *.exe
	del *.tds
	del *.map
else
	rm -f *.o *.obj *.exe *.tds *.map
endif


CopyInts.exe: CopyInts.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CopyStrings.exe: CopyStrings.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CopyVector.exe: CopyVector.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

InsertVector.exe: InsertVector.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CopyInts2.exe: CopyInts2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CopyStrings2.exe: CopyStrings2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

ReplaceStrings.exe: ReplaceStrings.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CopyInts3.exe: CopyInts3.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CopyIntsToFile.exe: CopyIntsToFile.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CopyIntsFromFile.exe: CopyIntsFromFile.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

GreaterThanN.exe: GreaterThanN.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CopyInts4.exe: CopyInts4.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

CountNotEqual.exe: CountNotEqual.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Generators.$(OBJEXT): Generators.cpp


FunctionObjects.exe: Generators.$(OBJEXT) FunctionObjects.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

FunctionObjects.$(OBJEXT): FunctionObjects.cpp

FBinder.exe: Generators.$(OBJEXT) FBinder.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

FBinder.$(OBJEXT): FBinder.cpp

BinderValue.exe: BinderValue.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PtrFun1.exe: PtrFun1.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PtrFun2.exe: PtrFun2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MemFun1.exe: MemFun1.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MemFun2.exe: MemFun2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

FindBlanks.exe: FindBlanks.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MemFun3.exe: MemFun3.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

ComposeTry.exe: ComposeTry.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

ComposeFinal.exe: ComposeFinal.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

FillGenerateTest.exe: Generators.$(OBJEXT) FillGenerateTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

FillGenerateTest.$(OBJEXT): FillGenerateTest.cpp

Counting.exe: Generators.$(OBJEXT) Counting.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Counting.$(OBJEXT): Counting.cpp

Manipulations.exe: Generators.$(OBJEXT) Manipulations.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Manipulations.$(OBJEXT): Manipulations.cpp

SearchReplace.exe: SearchReplace.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Comparison.exe: Comparison.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Removing.exe: Generators.$(OBJEXT) Removing.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Removing.$(OBJEXT): Removing.cpp

SortedSearchTest.exe: SortedSearchTest.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MergeTest.exe: Generators.$(OBJEXT) MergeTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MergeTest.$(OBJEXT): MergeTest.cpp

SetOperations.exe: Generators.$(OBJEXT) SetOperations.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

SetOperations.$(OBJEXT): SetOperations.cpp

Counted.$(OBJEXT): Counted.cpp


ForEach.exe: Counted.$(OBJEXT) ForEach.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

ForEach.$(OBJEXT): ForEach.cpp

Transform.exe: Counted.$(OBJEXT) Transform.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Transform.$(OBJEXT): Transform.cpp

CalcInventory.exe: CalcInventory.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TransformNames.exe: TransformNames.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

SpecialList.exe: SpecialList.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

NumericTest.exe: NumericTest.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_Generators.exe: TESTHEADER_Generators.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_NumStringGen.exe: TESTHEADER_NumStringGen.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_PrintSequence.exe: TESTHEADER_PrintSequence.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_NString.exe: TESTHEADER_NString.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_Counted.exe: TESTHEADER_Counted.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_Inventory.exe: TESTHEADER_Inventory.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_copy_if.exe: TESTHEADER_copy_if.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

