# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2004 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C07
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe


Borland:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	BasicSequenceOperations.exe \
	Noisy.$(OBJEXT) \
	VectorCoreDump.exe \
	StringDeque.exe \
	IndexingVsAt.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	WordList.exe \
	WordList2.exe \
	TokenIteratorTest.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	VectorOfBool.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Thesaurus.exe \
	Stlshape2.exe \
	Ring.exe \
	MatrixMultiply.exe \
	TESTHEADER_FileEditor.exe \
	TESTHEADER_Noisy.exe \
	TESTHEADER_PrintContainer.exe \
	TESTHEADER_TokenIterator.exe \
	TESTHEADER_assocGen.exe \
	TESTHEADER_SimpleGenerators.exe \
	TESTHEADER_PrintValarray.exe

Microsoft:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	RawStorageIterator.exe \
	BasicSequenceOperations.exe \
	Noisy.$(OBJEXT) \
	VectorOverflow.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	StringDeque.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	IndexingVsAt.exe \
	ListStability.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	Swapping.exe \
	WordList.exe \
	WordList2.exe \
	TokenIteratorTest.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	BitSet.exe \
	VectorOfBool.exe \
	AssociativeBasics.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Thesaurus.exe \
	Stlshape2.exe \
	Ring.exe \
	Valarray1.exe \
	Valarray2.exe \
	MatrixMultiply.exe \
	TESTHEADER_FileEditor.exe \
	TESTHEADER_Noisy.exe \
	TESTHEADER_PrintContainer.exe \
	TESTHEADER_TokenIterator.exe \
	TESTHEADER_assocGen.exe \
	TESTHEADER_SimpleGenerators.exe \
	TESTHEADER_PrintValarray.exe

g++:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	RawStorageIterator.exe \
	BasicSequenceOperations.exe \
	Noisy.$(OBJEXT) \
	VectorOverflow.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	StringDeque.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	IndexingVsAt.exe \
	ListStability.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	Swapping.exe \
	WordList.exe \
	WordList2.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	BitSet.exe \
	VectorOfBool.exe \
	AssociativeBasics.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Thesaurus.exe \
	Stlshape2.exe \
	Ring.exe \
	Valarray1.exe \
	Valarray2.exe \
	MatrixMultiply.exe \
	TESTHEADER_FileEditor.exe \
	TESTHEADER_Noisy.exe \
	TESTHEADER_PrintContainer.exe \
	TESTHEADER_TokenIterator.exe \
	TESTHEADER_assocGen.exe \
	TESTHEADER_SimpleGenerators.exe \
	TESTHEADER_PrintValarray.exe

edg:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	RawStorageIterator.exe \
	BasicSequenceOperations.exe \
	Noisy.$(OBJEXT) \
	VectorOverflow.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	StringDeque.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	IndexingVsAt.exe \
	ListStability.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	Swapping.exe \
	WordList.exe \
	WordList2.exe \
	TokenIteratorTest.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	BitSet.exe \
	VectorOfBool.exe \
	AssociativeBasics.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Thesaurus.exe \
	Stlshape2.exe \
	Ring.exe \
	MapVsHashMap.exe \
	Valarray1.exe \
	Valarray2.exe \
	MatrixMultiply.exe \
	TESTHEADER_FileEditor.exe \
	TESTHEADER_Noisy.exe \
	TESTHEADER_PrintContainer.exe \
	TESTHEADER_TokenIterator.exe \
	TESTHEADER_assocGen.exe \
	TESTHEADER_SimpleGenerators.exe \
	TESTHEADER_PrintValarray.exe

Metrowerks:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	RawStorageIterator.exe \
	BasicSequenceOperations.exe \
	Noisy.$(OBJEXT) \
	VectorOverflow.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	StringDeque.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	IndexingVsAt.exe \
	ListStability.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	Swapping.exe \
	WordList.exe \
	WordList2.exe \
	TokenIteratorTest.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	BitSet.exe \
	VectorOfBool.exe \
	AssociativeBasics.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Thesaurus.exe \
	Stlshape2.exe \
	Ring.exe \
	Valarray1.exe \
	Valarray2.exe \
	MatrixMultiply.exe \
	TESTHEADER_FileEditor.exe \
	TESTHEADER_Noisy.exe \
	TESTHEADER_PrintContainer.exe \
	TESTHEADER_TokenIterator.exe \
	TESTHEADER_assocGen.exe \
	TESTHEADER_SimpleGenerators.exe \
	TESTHEADER_PrintValarray.exe

DigitalMars:  \
	Intset.exe \
	WordSet.exe \
	Stlshape.exe \
	StringVector.exe \
	FileEditor.$(OBJEXT) \
	FEditTest.exe \
	Apply.exe \
	Reversible.exe \
	Inserters.exe \
	StreamIt.exe \
	StreambufIterator.exe \
	RawStorageIterator.exe \
	BasicSequenceOperations.exe \
	Noisy.$(OBJEXT) \
	VectorOverflow.exe \
	VectorCoreDump.exe \
	VectorInsertAndErase.exe \
	StringDeque.exe \
	DequeConversion.exe \
	DequeOverflow.exe \
	IndexingVsAt.exe \
	ListStability.exe \
	ListSpecialFunctions.exe \
	UniqueList.exe \
	ListVsSet.exe \
	Swapping.exe \
	WordList.exe \
	WordList2.exe \
	TokenIteratorTest.exe \
	Stack1.exe \
	Stack2.exe \
	Stack3.exe \
	BankTeller.exe \
	PriorityQueue1.exe \
	PriorityQueue2.exe \
	PriorityQueue3.exe \
	PriorityQueue4.exe \
	PriorityQueue5.exe \
	PriorityQueue6.exe \
	PriorityQueue7.exe \
	PriorityQueue8.exe \
	BitSet.exe \
	VectorOfBool.exe \
	AssociativeBasics.exe \
	NoisyMap.exe \
	AssocInserter.exe \
	WordCount.exe \
	WildLifeMonitor.exe \
	MultiSet1.exe \
	MultiSetWordCount.exe \
	Thesaurus.exe \
	Stlshape2.exe \
	Ring.exe \
	MapVsHashMap.exe \
	Valarray1.exe \
	MatrixMultiply.exe \
	TESTHEADER_FileEditor.exe \
	TESTHEADER_Noisy.exe \
	TESTHEADER_PrintContainer.exe \
	TESTHEADER_TokenIterator.exe \
	TESTHEADER_assocGen.exe \
	TESTHEADER_SimpleGenerators.exe \
	TESTHEADER_PrintValarray.exe

CodeWizard:
	CodeWizard *.cpp

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.o
	del *.obj
	del *.exe
	del *.tds
	del *.map
else
	rm -f *.o *.obj *.exe *.tds *.map
endif


Intset.exe: Intset.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

WordSet.exe: WordSet.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Stlshape.exe: Stlshape.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

StringVector.exe: StringVector.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

FileEditor.$(OBJEXT): FileEditor.cpp


FEditTest.exe: FileEditor.$(OBJEXT) FEditTest.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

FEditTest.$(OBJEXT): FEditTest.cpp

Apply.exe: Apply.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Reversible.exe: Reversible.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Inserters.exe: Inserters.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

StreamIt.exe: StreamIt.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

StreambufIterator.exe: StreambufIterator.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

RawStorageIterator.exe: Noisy.$(OBJEXT) RawStorageIterator.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

RawStorageIterator.$(OBJEXT): RawStorageIterator.cpp

BasicSequenceOperations.exe: BasicSequenceOperations.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Noisy.$(OBJEXT): Noisy.cpp


VectorOverflow.exe: Noisy.$(OBJEXT) VectorOverflow.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

VectorOverflow.$(OBJEXT): VectorOverflow.cpp

VectorCoreDump.exe: VectorCoreDump.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

VectorInsertAndErase.exe: Noisy.$(OBJEXT) VectorInsertAndErase.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

VectorInsertAndErase.$(OBJEXT): VectorInsertAndErase.cpp

StringDeque.exe: StringDeque.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

DequeConversion.exe: Noisy.$(OBJEXT) DequeConversion.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

DequeConversion.$(OBJEXT): DequeConversion.cpp

DequeOverflow.exe: Noisy.$(OBJEXT) DequeOverflow.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

DequeOverflow.$(OBJEXT): DequeOverflow.cpp

IndexingVsAt.exe: IndexingVsAt.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

ListStability.exe: Noisy.$(OBJEXT) ListStability.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

ListStability.$(OBJEXT): ListStability.cpp

ListSpecialFunctions.exe: Noisy.$(OBJEXT) ListSpecialFunctions.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

ListSpecialFunctions.$(OBJEXT): ListSpecialFunctions.cpp

UniqueList.exe: UniqueList.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

ListVsSet.exe: ListVsSet.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Swapping.exe: Noisy.$(OBJEXT) Swapping.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Swapping.$(OBJEXT): Swapping.cpp

WordList.exe: WordList.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

WordList2.exe: WordList2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TokenIteratorTest.exe: TokenIteratorTest.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Stack1.exe: Stack1.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Stack2.exe: Stack2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Stack3.exe: Stack3.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

BankTeller.exe: BankTeller.cpp


PriorityQueue1.exe: PriorityQueue1.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PriorityQueue2.exe: PriorityQueue2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PriorityQueue3.exe: PriorityQueue3.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PriorityQueue4.exe: PriorityQueue4.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PriorityQueue5.exe: PriorityQueue5.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PriorityQueue6.exe: PriorityQueue6.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PriorityQueue7.exe: PriorityQueue7.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

PriorityQueue8.exe: PriorityQueue8.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

BitSet.exe: BitSet.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

VectorOfBool.exe: VectorOfBool.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

AssociativeBasics.exe: Noisy.$(OBJEXT) AssociativeBasics.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

AssociativeBasics.$(OBJEXT): AssociativeBasics.cpp

NoisyMap.exe: Noisy.$(OBJEXT) NoisyMap.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

NoisyMap.$(OBJEXT): NoisyMap.cpp

AssocInserter.exe: AssocInserter.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

WordCount.exe: WordCount.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

WildLifeMonitor.exe: WildLifeMonitor.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MultiSet1.exe: MultiSet1.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MultiSetWordCount.exe: MultiSetWordCount.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Thesaurus.exe: Thesaurus.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Stlshape2.exe: Stlshape2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Ring.exe: Ring.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MapVsHashMap.exe: MapVsHashMap.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Valarray1.exe: Valarray1.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

Valarray2.exe: Valarray2.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

MatrixMultiply.exe: MatrixMultiply.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_FileEditor.exe: TESTHEADER_FileEditor.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_Noisy.exe: TESTHEADER_Noisy.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_PrintContainer.exe: TESTHEADER_PrintContainer.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_TokenIterator.exe: TESTHEADER_TokenIterator.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_assocGen.exe: TESTHEADER_assocGen.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_SimpleGenerators.exe: TESTHEADER_SimpleGenerators.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

TESTHEADER_PrintValarray.exe: TESTHEADER_PrintValarray.cpp
	$(CPP) $(CPPFLAGS) $(EXEFLAG)$@ $^
	$@

